# alpaca eval is
dpo_tldr_summarisation_eval_gpt4:
  prompt_template: "tldr_gpt4_eval_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "ranking_parser"
  batch_size: 1
