compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: 192.168.1.1
main_process_port: 8080
main_training_function: main
mixed_precision: 'no'
num_machines: 4
num_processes: 1
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
